### PR TITLE
Design description

### PR DESCRIPTION
**Pull request by sabbaka**

### CODE REVIEW

**Comment by spbnick** [comment]
This looks great, thank you Kyrill!

I just have a couple style requests:

* Please start the commit subject with a verb in imperative mood. In this case "Add" would be appropriate, I think.
* Please put the pictures in a folder named "playback_ui_cockpit_design", and put markdown into either "playback_ui_cockpit_design/index.md", or just "playback_ui_cockpit_design.md".

Thank you.

**Comment by sabbaka** [comment]
Corrected, check it, please.

**Comment by spbnick** [comment]
Merged, thank you!

**Comment by dpal** [comment]
In general even recorded sessions might not be for locally managed users. I wonder what patterns we have for user name search/autofill/filtering in other products and places. Might be worth checking with other projects.

Regarding configuration we should follow the general style if possible. Will it make sense have two different tabs one for configuration and one for playback? Do we have a precedent like this in some other place in Cockpit?

What about filtering by groups? It is not needed in the beginning but we should keep it in mind for future extension.

**Comment by sabbaka** [comment]
Thank you for response!

This current state of design is mostly to start such discussion with Cockpit designers.

One of my ideas is to use drop down - I've not found in Cockpit such examples and would like to see response of designers. In relation to other projects, - I'll make some research.

About configuration - I've described different ideas how to make and of them is to have two tabs ( sessions and configuration ). I also have not found anything like this in Cockpit.

About filtering by group - I've created issue.

**Pull request merged**
